### ISSUE TITLE
Error in the Console

### ISSUE THREAD

**Issue by strich3** [SergiFerry/PlayerNPC#11]
java.lang.NoSuchMethodError: 'void dev.sergiferry.playernpc.api.NPC$Personal.addCustomClickAction(dev.sergiferry.playernpc.api.NPC$Interact$ClickType, java.util.function.BiConsumer)

------

        dailyRewardnpc.addCustomClickAction(ClickType.RIGHT_CLICK, (x, y) -> {
            openDailyRewardMenu(player);
        });

------

Is something wrong with the code?

**Comment by SergiFerry** [comment]
You need to rebuild the artifacts, that's beacuse in the new version, its called the same but its not a void, because it returnes the custom action object, so you need to re compile
