### ISSUE TITLE
NPCs still show in tab list despite setting show on tab list to false

### ISSUE THREAD

**Issue by solman252** [SergiFerry/PlayerNPC#23]
After doing the /npcglobal setshowontablist ID false, the NPC still shows on the tablist under the name "&8[NPC] {ID}" (The ID is 4 characters long and changes when server is restarted or reloaded.)
The changes are saved to the config, however despite the value, it still shows.
I have also tried changing the name of the NPC on the tablist using both commands and editing config, however neither do anything, and the changes are overwritten by "&8[NPC] {ID}"

**Comment by solman252** [comment]
This happens on 1.19.2, Fixed in 1.19.3.

**Comment by SergiFerry** [comment]
Try out with the new 2023.2 version, which has fixed that issue
