### ISSUE TITLE
Placeholder API support?

### ISSUE THREAD

**Issue by TAC-Studios** [SergiFerry/PlayerNPC#40]
Not an issue but I was wondering if there will ever be PAPI support for this, would be useful

**Comment by SergiFerry** [comment]
There's actually PAPI placeholders support.

**Comment by TAC-Studios** [comment]
If I were to use it to set a name, do I just set the placeholder as the name? Otherwise, how would I go about doing that?

**Comment by SergiFerry** [comment]
Set the PAPI placeholder %placeholder% on the NPC Text, you can also use
PlayerNPC's own placeholders with {placeholder}

**Comment by TAC-Studios** [comment]
Thank you so much!
