### ISSUE TITLE
API can't use some methods.

### ISSUE THREAD

**Issue by zeroequalsone** [SergiFerry/PlayerNPC#8]
I can't use some methods. For example the "_updateText_" method.
Error: "**The method updateText() from the type NPC is not visible**"

**Comment by SergiFerry** [comment]
You need to use NPC.Personal if you're managing as an NPC only visible for 1 player, or NPC.Global if you will manage an NPC visible for everyone at the same time

**Comment by zeroequalsone** [comment]
Thank you for your fast and easy answer for my dumbass.
